# Copyright 2022-2023 Open Networking Foundation (ONF) and the ONF Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
{{- $fullname := include "common.names.fullname" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/stack: "{{ .Release.Namespace }}"
      annotations:
        checksum/configmap-app: {{ include (print $.Template.BasePath "/configmap-app.yaml") . | sha256sum }}
    spec:
      hostname: {{ $fullname }}
      tolerations:
        - key: node.kubernetes.io/not-ready
          effect: NoExecute
          tolerationSeconds: 30
        - key: node.kubernetes.io/unreachable
          effect: NoExecute
          tolerationSeconds: 30
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $fullname }}
          image: '{{ tpl .Values.images.igmpca.registry . }}{{ tpl .Values.images.igmpca.repository . }}:{{ tpl .Values.images.igmpca.tag . }}'
          imagePullPolicy: {{ tpl .Values.images.igmpca.pullPolicy . }}
          args:
            - "/app/igmpca"
            - "--api_address=:{{ .Values.igmpca.endpoints.grpc.port }}"
            {{- if .Values.defaults.cpuProfile }}
            - "--cpuprofile={{ .Values.defaults.cpuProfile }}"
            {{- end }}
            - "--logCaller={{ .Values.defaults.logCaller }}"
            - "--logLevel={{ tpl .Values.logLevel . }}"
            - "--rest_api_address=:{{ .Values.igmpca.endpoints.restapi.port }}"
          volumeMounts:
            - name: config
              mountPath: /app/configs
          ports:
            {{- range $name, $port := .Values.igmpca.endpoints }}
            - name: {{ $name }}
              containerPort: {{ ternary $port.targetPort $port.port (not (empty $port.targetPort)) }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /readz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            {{- if .Values.scheduleRules.preferStackPodsOnSameNode }}
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/stack
                      operator: In
                      values:
                        - {{ .Release.Namespace }}
              weight: 100
            {{- end }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            {{- if .Values.scheduleRules.preferStacksOnDifferentNodes }}
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - {{ .Chart.Name }}
              weight: 100
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ $fullname }}-app