# Copyright 2022-2023 Open Networking Foundation (ONF) and the ONF Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
{{- $fullname := include "common.names.fullname" . }}
{{- $namespace := .Release.Namespace }}
{{- $releaseName := .Release.Name }}
{{- $chartName := .Chart.Name }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}
  namespace: {{ $namespace }}
spec:
  type: ClusterIP
  ports:
    {{- range $name, $port := .Values.igmpca.endpoints }}
    {{- if or $port.enabled (not (hasKey $port "enabled")) }}
    - name: {{ $name }}
      port: {{ $port.port }}
      protocol: {{ $port.protocol | default "TCP" }}
      targetPort: {{ ternary $port.targetPort $port.port (not (empty $port.targetPort)) }}
    {{- end }}
    {{- end }}
  selector:
    app: {{ $chartName }}
    release: {{ $releaseName }}
{{- range $name, $port := .Values.igmpca.endpoints }}
{{- if not (empty $port.nodePort) }}
{{- if or $port.enabled (not (hasKey $port "enabled")) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullname }}-{{ $name }}-ext
  namespace: {{ $namespace }}
spec:
  type: NodePort
  ports:
    - name: {{ $name }}
      port: {{ $port.port }}
      protocol: {{ $port.protocol | default "TCP" }}
      targetPort: {{ ternary $port.targetPort $port.port (not (empty $port.targetPort)) }}
      nodePort: {{ $port.nodePort }}
  selector:
    app: {{ $chartName }}
    release: {{ $releaseName }}
{{- end }}
{{- end }}
{{- end }}